### ISSUE TITLE
Bug with frames

### ISSUE THREAD

**Issue by TomLewis** [radiant-ai/MilkyPixelart#1]
I know on your Modrinth plugin page its 1.19/1.20 but I the plugin mostly works on 1.18.2 already! its so close!

I initially wanted to just protect Paintings, but then I came across some of your other cool features, such as the pixelart preview! 

sadly this does not work on 1.18.2.

There is also a bug where you can just put a protected map in a frame, punch it off and it'll remove its protection as its lore is gone.

```
[23:09:04] [Server thread/INFO]: GodsDead issued server command: /pixelart preview 1
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] Exception in command: pixelart preview 1
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R3/map/CraftMapRenderer
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.managers.PixelartManager.getMapBytesLive(PixelartManager.java:433)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.managers.PixelartManager.populateItemFrame(PixelartManager.java:335)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.managers.PixelartManager.renderArtToUser(PixelartManager.java:293)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.managers.PixelartManager.renderArtFromItemStack(PixelartManager.java:251)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.managers.PixelartManager.renderArt(PixelartManager.java:241)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.commands.PixelartCommand.onPreview(PixelartCommand.java:134)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.acf.BaseCommand.execute(BaseCommand.java:513)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.acf.RootCommand.execute(RootCommand.java:99)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at MilkyPixelart-2.4.2.jar//fun.milkyway.milkypixelart.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2390)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2182)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1375)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1257)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R3.map.CraftMapRenderer
[23:09:04] [Server thread/ERROR]: [MilkyPixelart] [ACF] 	... 34 more
```

The banner editing seems to work on 1.18.2, as does the protection

**Comment by radiant-ai** [comment]
Hey! I cannot guarantee support for 1.18, this plugin is supported only because of my own server where I use it. I may look into this when I have some spare time.

Can you please try to reproduce the bug without any other plugins? Do you have any error in console when you punch out the map?

I have thousands of arts on server and there were no issues with protection, frames are very common for arts to be put in... and it would be a disaster if players could remove it that easily.

**Comment by radiant-ai** [comment]
@TomLewis You can try this snapshot (I actually found some time to try it out):
https://github.com/radiant-ai/MilkyPixelart/releases/tag/v.2.5.0-SNAPSHOT

**Comment by radiant-ai** [comment]
Given there is no additional comments on the issue I assume this was fixed with https://github.com/radiant-ai/MilkyPixelart/commit/afb68b021bf5d9fbe38dae86089b66ae65ab2f4a. I also tested myself on all supported versions.

**Comment by TomLewis** [comment]
Nah sorry I straight up just haven't had time to play yet! Kept open as I can't forget to test 🤣
